project:
  type: book

book:
  title: "ECTO: Theory Development Textbook"
  author:
    - name: "Noah van Dongen"
      affiliation: "Erasmus University Rotterdam"
  site-url: "https://<ORG_OR_USER>.github.io/<REPO>/"
  repo-url: "https://github.com/<ORG_OR_USER>/<REPO>"
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/01-introduction.qmd

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
