project:
  type: website

website:
  title: "ECTO"
  site-url: "https://<ORG_OR_USER>.github.io/<REPO>/"
  repo-url: "https://github.com/<ORG_OR_USER>/<REPO>"
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: documents.qmd
        text: Documents
      - href: logbook.qmd
        text: Logbook
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
