project:
  type: website
  render:
    - index.qmd
    - project-description.qmd
    - expert-identification.qmd
    - search-strategy.qmd
    - logbook.qmd
    - contact.qmd
  resources:
    - ../images

website:
  title: "ECTO"
  site-url: "https://<ORG_OR_USER>.github.io/<REPO>/"
  repo-url: "https://github.com/<ORG_OR_USER>/<REPO>"
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    logo: /images/ECTO_logo_NB.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: project-description.qmd
        text: Project Description
      - href: expert-identification.qmd
        text: Expert Identification
      - href: search-strategy.qmd
        text: Search Strategy
      - href: logbook.qmd
        text: Logbook
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: left
    smooth-scroll: true
